name: Build Android (Quest)
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Unity
        uses: kuler90/setup-unity@v1
        with:
          unity-modules: android
          install-path: /mnt/unity

      - name: Activate Unity
        uses: kuler90/activate-unity@v1
        with:
          unity-username: ${{ secrets.UNITY_EMAIL }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}

      - name: Build Unity
        uses: kuler90/build-unity@v1
        with:
          build-target: Android
          build-path: ./build/SanAndreasUnityVR.apk

      - uses: actions/upload-artifact@v4
        with:
          name: SanAndreasUnityVR-quest
          path: ./build/SanAndreasUnityVR.apk
