name: Get activation file
on: workflow_dispatch
jobs:
  get-alf:
    runs-on: ubuntu-latest
    steps:
      - name: Generate .alf via Unity docker image
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/root/project \
            unityci/editor:ubuntu-2020.3.26f1-base-3 \
            unity-editor -batchmode -nographics -logFile /dev/stdout \
              -createManualActivationFile -quit
      - uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: "*.alf"
          if-no-files-found: error
